version: '3'

services:
  rabbitmq.publisher:
    image: rabbitmq.publisher
    build:
      context: .
      dockerfile: RabbitMQ.Publisher/Dockerfile
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  default:
    external:
      name: isolated