version: '3'

services:
  rabbitmq.publisher:
    image: rabbitmq.publisher:dev
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_rabbitmq.publisher$
    volumes:
      - C:\adfenix-codebase\RabbitMQ.Publisher\RabbitMQ.Publisher:/app
      - C:\Users\Shoieb\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_rabbitmq.publisher$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_rabbitmq.publisher$ bin/Debug/netcoreapp2.0/RabbitMQ.Publisher.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
